name: Docker Chrome Headless Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_call:
    inputs:
      node_image:
        description: 'Node image version from official node docker hub'
        default: 'lts'
        required: false
        type: string

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node_image: 'lts'
      - name: Build image test
        run: docker build ./chrome-headless --tag llioss/node-chrome-headless:${{ inputs.node_image }} --build-arg TARGET_NODE_VERSION=${{ inputs.node_image }}

  build:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Publish Docker image
      run: docker push llioss/node-chrome-headless:${{ inputs.node_image }}
