name: Docker Chrome Headless Image CI

env:
  NODE_IMAGE_VERSION: lts

on:
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    if: ${{ github.ref != 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          node_image: 'lts'
      - name: Build image test
        run: docker build ./chrome-headless --tag llioss/node-chrome-headless:${{ env.NODE_IMAGE_VERSION }} --build-arg TARGET_NODE_VERSION=${{ env.NODE_IMAGE_VERSION }}
