name: Publish Docker Chrome Headless

env:
  NODE_IMAGE_VERSION: lts

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build image test
      run: docker build ./chrome-headless --tag llioss/node-chrome-headless:${{ env.NODE_IMAGE_VERSION }} --build-arg TARGET_NODE_VERSION=${{ env.NODE_IMAGE_VERSION }}

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

    - name: Publish Docker image
      run: docker push llioss/node-chrome-headless:${{ env.NODE_IMAGE_VERSION }}
