name: Docker Chrome Headless Image CI

env:
  NODE_IMAGE_VERSION: lts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./chrome-headless --tag llioss/node-chrome-headless:${{env.NODE_IMAGE_VERSION}} --build-arg TARGET_NODE_VERSION=${{env.NODE_IMAGE_VERSION}}
